### ISSUE TITLE
updateSettings does not work with maxSize properties

### ISSUE THREAD

**Issue by sigma-technology** [elninotech/uppload#102]
**Describe the bug**
Version 2.6.1
When using the `updateSettings` method to change the `maxSize` property, the changes are not reflected when an upload is later attempted.  The issue occurs regardless of whether you are using the Crop service or not.

The same issue is also present with:
- maxWidth
- maxHeight
- compression (I think)
- possibly others, I haven't been able to test them all

**To Reproduce**

    const uppload = new Uppload({
        maxSize: [1200, 900]
    });
    uppload.updateSettings({
        maxSize: [600, 450]
    });
    // Then upload an image wider than 600px and it will be uploaded at up to 1200px wide
    // If no maxSize is specified upon instantiation, the image size is unlimited

**Expected behavior**
The size of the next uploaded image should be restricted by the changed parameters specified using `updateSettings`.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version: Latest

**Comment by AnandChowdhary** [comment]
Thanks for finding this issue, @sigma-technology! I don't know why this wasn't discovered before, my fault. This is fixed and deployed in `v.2.7.0`.

**Comment by sigma-technology** [comment]
Thank you so much for the fast turnaround on these.  I do fully intend on contributing to this repository with actual code very soon, rather than just logging lots of bugs :-)
