### ISSUE TITLE
Add possibility to translate "cancel" and "upload" in effects bar

### ISSUE THREAD

**Issue by tpinne** [elninotech/uppload#107]
**Is your feature request related to a problem? Please describe.**
Currently those labels are not translated at all.

**Describe the solution you'd like**
Translation for those labels.

**Comment by AnandChowdhary** [comment]
Thanks! I’ll also browse through the code and see if I missed any other labels.

**Comment by AnandChowdhary** [comment]
Found another one! Added these translations:

- `cancel`
- `upload`
- `close`

**Comment by AnandChowdhary** [comment]
This is deployed in `v2.7.1`.
