### ISSUE TITLE
Add additional data to uploader function?

### ISSUE THREAD

**Issue by jimmiejackson414** [elninotech/uppload#110]
**Is your feature request related to a problem? Please describe.**
I'm not even sure if this is exists already or not, but I can't figure out from reading the docs how I might add additional data to the xhrUploader. I'd like to add a simple `{user_id: user.id}`.

**Describe the solution you'd like**
Similar to the axios.js library, I'd like to be able to add additional data to the uploader to be sent to my API endpoint. 

**Describe alternatives you've considered**

**Additional context**
I currently have something along the lines of:
```
this.uppload = new Uppload({
    customClass: 'avatar-upload',
    lang: en,
    uploader: xhrUploader({
        endpoint: `${apiUrl}/update_avatar`,
        method: 'POST',
        responseKey: 'avatar_url',
        settingsFunction: xmlHttp => {
            xmlHttp.setRequestHeader('Accept', 'application/json');
            xmlHttp.setRequestHeader('Authorization', 'Bearer ' + this.currentUser.token);
        },
   }),
});
```
If this ability does already exist, where can I find that in the docs?

Thanks!

**Comment by sigma-technology** [comment]
@jimmiejackson414 You can simply add custom headers to accomplish this, for example:

```
this.uppload = new Uppload({
    customClass: 'avatar-upload',
    lang: en,
    uploader: xhrUploader({
        endpoint: `${apiUrl}/update_avatar`,
        method: 'POST',
        responseKey: 'avatar_url',
        settingsFunction: xmlHttp => {
            xmlHttp.setRequestHeader('Accept', 'application/json');
            xmlHttp.setRequestHeader('Authorization', 'Bearer ' + this.currentUser.token);
            xmlHttp.setRequestHeader('user_id', user_id);
        },
   }),
});
```

Then just grab the headers from the HTTP request on the server side/your API endpoint and you should be good to go.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @jimmiejackson414, and thanks @sigma-technology for the solution. It makes a lot of sense to use `xhrUploader` and configure it with additional data in headers.

If you don't want to do that, however, you can write your own uploader from scratch, for example like this based on our [Fetch uploader](https://uppload.js.org/uploaders/fetch):

```ts
const uploader = () => {
  return file =>
    new Promise((resolve, reject) => {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("user_id", user.id);
      window
        .fetch(
          "https://example.com/endpoint",
           {
              method: "POST",
              body: formData
           }
        )
        .then(response => {
          if (!response.ok) throw new Error("errors.response_not_ok");
          return response.json();
        })
        .then(json => resolve(json.url))
        .catch(() => reject("errors.response_not_ok"));
    });
};

new Uppload({ uploader });
```

For more information about creating a custom controller, read this article: [Writing a custom controller](https://uppload.js.org/uploaders/custom-uploader)

**Comment by jimmiejackson414** [comment]
Ahh well I feel slightly like an idiot now haha. I definitely misunderstood the docs. To be honest, it might be helpful to add these examples to the docs? I'll go ahead and close, and thanks to both of you for your help!
