### ISSUE TITLE
Effects Progress

### ISSUE THREAD

**Issue by davehibshman** [elninotech/uppload#111]
**Is your feature request related to a problem? Please describe.**
When loading largish files and using effects like flip, contrast, sepia, etc. it can take some seconds.  Showing some progress, even if only non-determinant like a spinner, would be helpful.  I clicked the Horizontal flip about 3 times before it seemed to responded and then realized it was working all the while.

**Describe the solution you'd like**
Indication something is happening when I move the slider to apply an effect.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AnandChowdhary** [comment]
This is really interesting. I haven’t tried uploading a super larger file, but we have to note that canvas to blob, which takes all this time, is thread blocking. I’ll set it up in a way that we emit a “working” and “finished working” event before and after, and show a loading state during.

**Comment by AnandChowdhary** [comment]
I've added a new loading state (called "processing"), along with emitters, that work during image processing. This is deployed in `v2.7.3`.
