### ISSUE TITLE
Crop section shows some console logs

### ISSUE THREAD

**Issue by chanlito** [elninotech/uppload#13]
Something like the following:

<img width="1030" alt="screen shot 2018-05-29 at 3 20 18 pm" src="https://user-images.githubusercontent.com/15667259/40646605-d77a90d6-6353-11e8-9c3a-e06192089908.png">

Is this from uppload? or its dependencies?

Thanks for this awesome uploader btw. ❤️

EDIT: BTW the vue wrapper package.json seems out of dated.

**Comment by AnandChowdhary** [comment]
Hi @chanlito, thanks for reporting this! I pushed an update to cropping yesterday and must've left these in by mistake. I'll push a new release today with fixes to both these issues.
