### ISSUE TITLE
accept only image/* type of file

### ISSUE THREAD

**Issue by saqueib** [elninotech/uppload#150]
currently we you select a file you see all the file selectable in finder window, if you can add some option to select only image/* it will be great. I have used dropzone they have this feature https://www.dropzonejs.com/#config-acceptedFiles

Let me know if its already there

**Comment by AnandChowdhary** [comment]
Yes, you can specify the MIME types for the local service: https://uppload.js.org/services/local:

> In the constructor parameter, you can specify the mime types you want to support and the maximum file size. By default, JPG, PNG, and GIF images are allowed, since Uppload is primarily an image uploader (but you can easily extend it to be a general-purpose file uploader).

```ts
const localServiceWithVideo = new Local({
  maxFileSize: 25000,
  mimeTypes: ["image/png", "image/jpeg", "video/mp4"]
});
```
