### ISSUE TITLE
Unable to use "Rotate" service

### ISSUE THREAD

**Issue by vishal2947** [elninotech/uppload#151]
Hello,

I am not able to see "Rotate" service anywhere in the doc but I can see it in demo plugin. 

Can someone point me in the right direction?

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @vishal2947! I've updated relevant docs here: https://uppload.js.org/effects/

Quick note: "Services" are ways to select a file, like Unsplash or Camera. "Effects" are ways to edit files before uploading them.
