### ISSUE TITLE
Reject promise inside uploadFunction

### ISSUE THREAD

**Issue by pegler** [elninotech/uppload#16]
**Describe the bug**
When using a custom uploadFunction, if I call reject the promise, it displays "uploaded" without any indication a problem happened.

**To Reproduce**
Fiddle: http://jsfiddle.net/27xk8rvm/3/

As you can see that uploadFunction always call reject. If you simply try to upload any file, it will display "uploaded" without any error message or way to proceed.

That as a minimal example. In our testing, our server is sending back an error message to the client and we are calling reject in the fetch's then clause.

**Expected behavior**
The error should be displayed and the user should be given the opportunity to upload a different file.

I found a workaround where I show the error message myself and then change the page. Here's a fiddle with the workaround: http://jsfiddle.net/qpj6rabx/6/

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome 69

**Comment by AnandChowdhary** [comment]
Hey @pegler! Thanks for finding this issue. You're right, we should show the promise rejection message, with a fallback to a generic error message, as part of the rejection.

I'm going to look into it and deploy a patch within the week. 😄

**Comment by pegler** [comment]
great, thanks! this is a great widget. Is there anywhere we can donate to buy you a coffee or a beer?

**Comment by AnandChowdhary** [comment]
Nah, we're just happy that great developers like you are using Uppload. 👍
