### ISSUE TITLE
Ability to specify crop.startSize

### ISSUE THREAD

**Issue by pegler** [elninotech/uppload#17]
Currently the cropping step defaults the cropped section to 50% of the image size, but we'd like to default to 100%. This is because given our use case, most users are not going to need to crop the image. It'd be great if we could specify startSize in the configuration like we can for aspectRadio, maxSize, and minSize.

https://github.com/elninotech/uppload/blob/1fdc2379eb203de122e78fa4830c9e44bd7413d8/modules/services/crop.js#L68

**Comment by AnandChowdhary** [comment]
In v0.3.4, you can now use the setting `crop.startSize` just like `crop.aspectRadio`:

```js
const squareProfilePicture = new Uppload({
    value: "https://randomuser.me/api/portraits/men/17.jpg",
    crop: {
        aspectRatio: 1,
        maxSize: [1024, 1024, "px"],
        minSize: [64, 64, "px"],
        startSize: [100, 100, "%"]
    }
});
```

**Comment by pegler** [comment]
Fantastic, thanks!
