### ISSUE TITLE
disable clicking outside the modal

### ISSUE THREAD

**Issue by jeffbabuyo** [elninotech/uppload#185]
Is there a way to disable the modal from closing when I clicked outside the modal area? Currently, when I click outside the modal area the modal is close.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @jeffbabuyo. No, there isn't a way to prevent closing the modal when you click outside, but I can add this feature for you.

**Comment by AnandChowdhary** [comment]
You can now add the key `disableModalClickClose` when configuring Uppload:

```ts
const image = new Uppload({
  // your settings,
  disableModalClickClose: true
})
```

This will make sure the "close" button on the top right closes the modal, not clicking anywhere on the modal.
