### ISSUE TITLE
ASP.net demo is a 404

### ISSUE THREAD

**Issue by alexjamesbrown** [elninotech/uppload#20]
In the docs,
http://venkatbaggu.com/file-upload-in-asp-net-mvc-using-dropzone-js-and-html5/

is a 404...

**Comment by victorlap** [comment]
Hi!

Thanks for notifying us. I've update the link to the new location.

**Comment by alexjamesbrown** [comment]
@victorlap cool -
but that's for using Dropzone? Are they comparable?

**Comment by AnandChowdhary** [comment]
@alexjamesbrown Yes. The backend is the same as what would be if you were using a native HTML form submission, which is the same as if you were using Dropzone.
