### ISSUE TITLE
can coexist with drawers

### ISSUE THREAD

**Issue by philohelp** [elninotech/uppload#219]
**Describe the bug**
I dont know if this should be a bug or a feature request. I try to use Uppload (V3) at the same moment I have rc-drawer opened. I can easily do that with modals but unfortunately I have no success with the Uppload's one. 

**To Reproduce**
See screenshots to have a clear idea on what's going on. Uppload remains hidden by the drawer's mask.

**Expected behavior**
Make Uppload appear at the top level.

**Screenshots**
This is the result I get with Uppload : 
![drawerAndUppload](https://user-images.githubusercontent.com/12623963/83338919-3cc6a900-a2c9-11ea-90f4-5d07020cbf60.jpg)

And this is the result with a basic bulma modal (hosting the current media-library and uploader) that I'd need to achieve with Uppload too (I can't get rid of the rc-drawers, a big part of the app is based on them) :

![drawerAndModal](https://user-images.githubusercontent.com/12623963/83338970-88795280-a2c9-11ea-8a07-2e2e3f1d0635.jpg)

Many thanks in advance

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser Chrome
 - Version 71

**Comment by AnandChowdhary** [comment]
This seems like a `z-index` issue. Do you think you can create CodeSandbox or JSFiddle demo? Then, I can show you which value to add. Adding one CSS rule should fix this.

**Comment by philohelp** [comment]
Ok thanks I've created a demo on stackblitz : [https://react-qcyzps.stackblitz.io/](https://react-qcyzps.stackblitz.io/)
It uses the same rc-drawer.

**Comment by MaximusBaton** [comment]
Hey @philohelp you problem comes from the drawer.
When opening the drawer it moves to the right all the root elements inside `body` tag.
As the upploader is one of the root element it also being affected by the `transform` property.
The easiest solution for you would be to add the following in your stylesheets:
```
.uppload-container {
    transform: initial !important;
}
```

**Comment by philohelp** [comment]
Well done !

**Comment by AnandChowdhary** [comment]
@all-contributors please add @MaximusBaton for bugs
