### ISSUE TITLE
Is Uppload supposed to convert to png?

### ISSUE THREAD

**Issue by robisaks** [elninotech/uppload#22]
**Describe the bug**
With Firebase preset, every image uploaded is converted to png. This drastically increases the size of the files. Is this expected behavior, or a bug?

**To Reproduce**
1. Use Firebase preset
2. Upload and crop a jpg image
3. Browse Firebase storage via dashboard
4. Observe png files 6x the size of jpg

**Expected behavior**
Upload jpg if there isn't transparency to keep the size lower. Firebase can be costly if not optimized.

**Comment by AnandChowdhary** [comment]
This has been added in v0.3.6. There is a significant difference in uploaded file sizes:

**Size comparison:**
- `image/jpeg` with quality `0.5` gives 18.25 KB image
- Default settings (high-quality PNG) uploads a 307.52 KB image

You can implement it as in [the demo](https://elninotech.github.io/uppload/):

```js
const profilePicture = new Uppload({
    uploadFormat: {
        type: "image/jpeg",
        quality: 0.5
    }
});
```
