### ISSUE TITLE
off calls emitter.on?

### ISSUE THREAD

**Issue by RichardJohnn** [elninotech/uppload#236]
https://github.com/elninotech/uppload/blob/9e5c8730ee484b7289b28dbc1d4c5b7bdde27a3d/src/uppload.ts#L877-L879 should this call emitter.off instead of on?

**Comment by AnandChowdhary** [comment]
Wait, what? Of course! I can't believe that I was so silly to have missed this and nobody pointed this out until now. 😄

**Comment by AnandChowdhary** [comment]
@all-contributors please add @RichardJohnn for bugs

**Comment by AnandChowdhary** [comment]
This is fixed in `v3.2.0`. Thanks for pointing it out!
