### ISSUE TITLE
Possibility to use with Ruby on Rails together with Cloudinary

### ISSUE THREAD

**Issue by joseh-henrique** [elninotech/uppload#239]
Looking for examples of better Rails uploads with Cloudinary, I found this gem. Is it possible to use together with Rails and Cloudinary? If not, could there be any possibility? I am impressed with this finding.

**Comment by AnandChowdhary** [comment]
Yes, you can set up your own upload server written in Ruby on Rails and use the Cloudinary API and upload files there. However, Cloudinary has their own file uploading function, and perhaps it'd be easier to use that directly?

**Comment by joseh-henrique** [comment]
What impressed me was the work you had in receiving and treating the image, so the sending part continues with Cloudinary, I would love to use it this way, together with Rails, so my question, how to adjust plugins for use in Rails with handling for shipping by Cloudinary?

**Comment by AnandChowdhary** [comment]
You wouldn't have to adjust the plugins, all you need to do is set up your Ruby on Rails endpoint that uploads to Cloudinary using their API. Uppload would simply send the image to your endpoint, and then where the image goes is entirely up to you. :)
