### ISSUE TITLE
Remove Circle CI

### ISSUE THREAD

**Issue by AnandChowdhary** [elninotech/uppload#247]
Circle CI is throwing errors for warning, preventing auto-merge PRs etc.

We already have multiple CIs, like GitHub Actions, Travis CI, and Azure Pipelines, so removing Circle CI is not a problem.

**Comment by AnandChowdhary** [comment]
@thlassche You'll have to log in to http://travis-ci.com or https://travis-ci.org and remove it like so: https://stackoverflow.com/a/30875819/1656944 (I don't have access to the `elninotech` account on Travis so I have to bother you).

**Comment by victorlap** [comment]
Done 👌
