### ISSUE TITLE
[VueJS wrapper] UPPLOAD_VERSION not defined in services.js

### ISSUE THREAD

**Issue by frossigneux** [elninotech/uppload#26]
I installed uppload using `yarn add uppload uppload-vue`, and installed also `sass-loader and node-sass` (to fix some errors). I create a new view based on the example template.
My project compiled successfully using webpack-dev-server started from `vue ui`.

However, when I load the app in my browser, I see:

> [Vue warn]: Error in mounted hook: "ReferenceError: UPPLOAD_VERSION is not defined"

If I replace the _UPPLOAD_VERSION_ by the version string in the services.js (under _node_modules_), all components load fine.

How can I fix this error? Is it a webpack config problem?
Thanks

**Comment by pastorryanhayden** [comment]
I'm running into this same issue using it with Laravel.

**Comment by AnandChowdhary** [comment]
This has been fixed in v1.1.0, we no longer have the Webpack build variable, it should be working perfectly now. 😄
