### ISSUE TITLE
Firefox Browser Support Issue

### ISSUE THREAD

**Issue by OlehStay** [elninotech/uppload#27]
TypeError: ["preview", "crop", "uploading", "uploaded"].includes is not a function

try to load uppload demo on firefox
see console

Desktop
OS X Yosemite 10.10.5
Firefox v 41.0

**Comment by AnandChowdhary** [comment]
Aah, it’s an Array.prototype.includes issue. I think it should be fixed if you use the Uppload version with polyfills, or manually add the array.includes polyfill.

I’ll have a more detailed look later today.

**Comment by AnandChowdhary** [comment]
Yes, it’s supported Firefox 43 onwards. https://caniuse.com/#feat=array-includes

**Comment by AnandChowdhary** [comment]
This has been fixed in v1.1.0, we're no more relying upon `Array.prototype.includes`, instead using `indexOf` (IE 9+).
