### ISSUE TITLE
Save locally

### ISSUE THREAD

**Issue by seritpt** [elninotech/uppload#29]
Does anybody know if its possible to save the image locally?
I mean without using firebase storage.

I see the image canvas generated in console.log but I need to save it locally without using other sites.

Demo > https://jsfiddle.net/BUUdesign/7h603fbo/

Thanks a lot

**Comment by AnandChowdhary** [comment]
Hi @seritpt, sure, you can just create your own `uploadFunction`.

I've updated your fiddle with a (very basic) sample function: https://jsfiddle.net/anandchowdhary/n6s8z1aq/10/
