### ISSUE TITLE
Save locally without download file

### ISSUE THREAD

**Issue by seritpt** [elninotech/uppload#30]
Thanks you so much again for the all other helps.
What I'm trying to do is use your upload for multiple uploaders (where you already helped my last week) without use other sites or services  and what I need for now is to save locally on server without download the file. 

I think that I have to save somewhere in hidden canvas the generated image and send that code info by Ajax to PHP to save de generated image on server and return that url to input text box.

References:
http://html2canvas.hertzen.com
http://stackoverflow.com/questions/11511511/how-to-save-a-png-image-server-side-from-a-base64-data-string

DEMO: https://jsfiddle.net/BUUdesign/ktL03nb5/

**Comment by seritpt** [comment]
Can you help me with that please? :-) Many thanks in advance.

**Comment by seritpt** [comment]
Any news? :-D

**Comment by thlassche** [comment]
Hi @seritpt,

I fixed your script (profile picture 2):
https://jsfiddle.net/ajxokm2h/8/

It now uploads to the server and shows it.

**Comment by seritpt** [comment]
> Hi @seritpt,
> 
> I fixed your script (profile picture 2):
> https://jsfiddle.net/ajxokm2h/8/
> 
> It now uploads to the server and shows it.

Wow! Many, many, many thanks. I'm going to test it :-)

**Comment by seritpt** [comment]
> Hi @seritpt,
> 
> I fixed your script (profile picture 2):
> https://jsfiddle.net/ajxokm2h/8/
> 
> It now uploads to the server and shows it.

It works Perfect :-D
