### ISSUE TITLE
Failed to execute 'fetch' on 'Window'

### ISSUE THREAD

**Issue by bluee** [elninotech/uppload#31]
**Describe the bug**
When trying to upload a file using uppload v1.1.0 it fails

Error:
Failed to execute 'fetch' on 'Window': The provided value is not of type '(sequence<sequence<ByteString>> or record<ByteString, ByteString>

To view error look in console log or close modal window. Modal wrongly says file was uploaded.

**To Reproduce**
Set endpoint on an Angular v2-7 app and try and upload

Example:
Go to https://stackblitz.com/edit/uppload-angular-aq3awx and upload a file.
You will then see exception:

Failed to execute 'fetch' on 'Window': The provided value is not of type '(sequence<sequence<ByteString>> or record<ByteString, ByteString>

**Expected behavior**
File would be uploaded to endpoint. Endpoint is never touched

**Comment by AnandChowdhary** [comment]
You are right, this needs a fix.

**Comment by focussing** [comment]
Hello!

What would be the workaround for this issue?
I am struggling already for a few hours....

**Comment by AnandChowdhary** [comment]
This is super high priority in my list of work to do, but the current workaround would probably be to create a custom function, `uploadFunction`, which takes the uploaded image as a parameter and sends it to your server using `axios` or `window.fetch`.

You can pass your custom upload function in the constructor.

**Comment by focussing** [comment]
Thank you very much for this super fast response!

So I had this which gave the above error

```
				endpoint: {
					method: 'POST',
					url: '/file-upload.php'
				},
```


And when I use this I get another error in a red messagebox:
Error: SyntaxError: Unexpected end of JSON input.

```
				uploadFunction: (file, metadata) => {
					return new Promise((resolve, reject) => {
						fetch('/file-upload.php', {
							method: 'POST',
							body: file
						})
							.then(response => response.json())
							.then(json => {
								let url = json.url;
								resolve(url);
							})
							.catch(error => reject(error));
					});
				}
```

The PHP function I use is working with another application that uses dropzone:

```
<?php

header('Access-Control-Allow-Origin: *');

// from http://www.startutorial.com/articles/view/how-to-build-a-file-upload-form-using-dropzonejs-and-php

$ds = DIRECTORY_SEPARATOR;
$storeFolder = 'uploads';

if (!empty($_FILES)) {
	$tempFile = $_FILES['file']['tmp_name'];
	$targetPath = dirname(__FILE__) . $ds . $storeFolder . $ds;
	$targetFile = $targetPath . $_FILES['file']['name'];
	move_uploaded_file($tempFile, $targetFile);
}
?>
```

**Comment by AnandChowdhary** [comment]
Looks like the error is that your PHP server is not responding with any JSON.

I'd suggest you change the `if` block with:

```php
if (!empty($_FILES)) {
	$tempFile = $_FILES['file']['tmp_name'];
	$targetPath = dirname(__FILE__) . $ds . $storeFolder . $ds;
	$targetFile = $targetPath . $_FILES['file']['name'];
	move_uploaded_file($tempFile, $targetFile);
        echo json_parse(array("url" => $targetFile));
}
```

**Comment by focussing** [comment]
Tried that but same problem...

**Comment by focussing** [comment]
Now I made a new upload function based on axios.
No error messages, it says uploaded! But no file is in the uploads folder...

```
uploadFunction: file => {
	return new Promise((resolve, reject) => {
		var formData = new FormData();
		formData.append('image', file);
		axios
			.post('/file-upload.php', formData, {
				headers: {
					'Content-Type': 'multipart/form-data'
				}
			})
			.then(response => {
				console.log(response);
				resolve(response);
			})
			.catch(error => reject(error));

			// fetch('/file-upload.php', {
			// 	method: 'POST',
			// 	body: file
			// })
			// .then(response => response.json())
			// .then(json => {
			// 	let url = json.url;
			// 	resolve(url);
			// })
	});
}
```

**Comment by focussing** [comment]
It seems that there is no data to be uploaded?
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAPc0lEQ…gqmyqx7tN1jOFxo9y3uZyJcSmHqRCVfYD0WZlF2eLB/wL6ZbyWE3VoVwAAAABJRU5ErkJggg==
Home.vue?76f2:123 
{data: "", status: 200, statusText: "OK", headers: {…}, config: {…}, …}
config: (...)
data: ""
headers: (...)
request: (...)
status: (...)
statusText: (...)

Home.vue?76f2:152 File uploaded! 
{…}
config: Object
data: ""
headers: Object
access-control-allow-origin: (...)
connection: (...)
content-length: (...)
content-type: (...)
date: (...)
host: (...)
x-powered-by: (...)
__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
...
__proto__: Object
request: (...)
status: 200
statusText: "OK"
__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}

....
```

**Comment by seritpt** [comment]
> Hello!
> 
> What would be the workaround for this issue?
> I am struggling already for a few hours....

I'm waiting since 19/3 of this year :-P

**Comment by seritpt** [comment]
What are you trying to do?
What I'm trying it's to have my own function to upload with PHP but it seems not send values of image only the "Request Payload" in php file.
Gives me the JSON error to. I need to save in my server and return that url address to be used in input text box.

**Comment by focussing** [comment]
Implemented vue-dropzone to check whether my .php script works - flawless...
4 minutes work to get a working dropzone...
Does it make sense to fallback to an earlier version?
BTW; the given example does no real uploading of a file...

**Comment by AnandChowdhary** [comment]
> It seems that there is no data to be uploaded?
> 
> ```
> data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAPc0lEQ…gqmyqx7tN1jOFxo9y3uZyJcSmHqRCVfYD0WZlF2eLB/wL6ZbyWE3VoVwAAAABJRU5ErkJggg==
> Home.vue?76f2:123 
> {data: "", status: 200, statusText: "OK", headers: {…}, config: {…}, …}
> config: (...)
> data: ""
> headers: (...)
> request: (...)
> status: (...)
> statusText: (...)
> 
> Home.vue?76f2:152 File uploaded! 
> {…}
> config: Object
> data: ""
> headers: Object
> access-control-allow-origin: (...)
> connection: (...)
> content-length: (...)
> content-type: (...)
> date: (...)
> host: (...)
> x-powered-by: (...)
> __ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
> ...
> __proto__: Object
> request: (...)
> status: 200
> statusText: "OK"
> __ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
> 
> ....
> ```

As you can see here, it's because the data is sent in base 64 encoded format. You can either change it to a file using `new File()` in the JavaScript or convert the string to a file on the PHP side.

> Implemented vue-dropzone to check whether my .php script works - flawless...
> 4 minutes work to get a working dropzone...
> Does it make sense to fallback to an earlier version?
> BTW; the given example does no real uploading of a file...

I understand this, and I hope that Uppload soon will also have a much simpler onboarding process for new developers and would plug-and-play more easily. There is work to be done, but this is only something I'm working on in my free time. 😉

**Comment by AnandChowdhary** [comment]
I'll add the `help-wanted` tag, so if there are any developers who want to work on this, I'll be happy to code review, but I can only get into the fix (or a new version, as planned) in a few weeks time.

**Comment by focussing** [comment]
I just got dropzone for testing the PHP. 
Uppload is really great, especially with the preview and crop functions. 

I understand what you are saying; I hope you can find some time to figure out what is wrong because I have the impression that more devs are waiting for this. It could be very easy to solve because the problems reproduce easily. And if you test with a working backend a fix might be found soon....

**Comment by focussing** [comment]
Converting the string to a file; would that be the solution?
How should I do that?

**Comment by seritpt** [comment]
> I just got dropzone for testing the PHP.
> Uppload is really great, especially with the preview and crop functions.
> 
> I understand what you are saying; I hope you can find some time to figure out what is wrong because I have the impression that more devs are waiting for this. It could be very easy to solve because the problems reproduce easily. And if you test with a working backend a fix might be found soon....

Have you got any demo of that script working with crop? Thanks in advance :-)

**Comment by thlassche** [comment]
Just released 1.1.1 that fixes this.

**Comment by focussing** [comment]
Great, thanks!
Where can I find the fix?
`npm install uppload` and `npm install uppload-vue` are not updated to 1.1.1

**Comment by thlassche** [comment]
@focussing Can you retry?

**Comment by focussing** [comment]
It installs :)
So basically this issue is rightfully closed.

But it does not fix my problems though....

**Comment by thlassche** [comment]
@focussing I think you should change
```
formData.append('image', file);
```
to:
```
formData.append('file', file);
```
Because you check for 'file' in PHP and not 'image'

**Comment by focussing** [comment]
@thlassche You are absolutely right. My mistake.
However that is not where the real problem lies. Still no file is uploaded.
I tested that also with text files, pdf etc.
The example provided works, but there is no file uploaded, just a promise is returned.

Another thing 1:
From what I understand is that there is an conversion to Base64 (probably caused by the crop functionality?).
I think that should be hidden from the user. It is an internal affair of the module.
Also the code examples provided in the docs and the docs themselves do not mention anything about Base64.

Another thing 2:
From the upload promise the URL is returned; from what I notice from the error message the "endpoint" property gives, it should be JSON encoded. Can't find anything about that also (the suggestion mentioned above regarding `json_parse` does not work).


I would suggest:
1) Make the upload function really work; that is the core function of this module.
For all file types.
If you use the php function as described here http://www.startutorial.com/articles/view/how-to-build-a-file-upload-form-using-dropzonejs-and-php it should work without issues. That is working in my Vue-cli3 project even with local files.

2) For image files use the cropping functionality if set by a (new) property. Keep a possible base64 conversion hidden/internal.


I really think uppload could be great to use and I am looking forward to using it. However last friday I lost quite an amount of time trying to get it working, and when it didn't I had to turn back to dropzone for now (sorry!).

**Comment by seritpt** [comment]
Any demo? Thanks in advance :-)

**Comment by focussing** [comment]
Sorry, it's not working so cannot provide demo.

**Comment by seritpt** [comment]
> Sorry, it's not working so cannot provide demo.

I'm just trying to create an upload with Uppload.js to just simple save the generated image in my server folder. Any Ideia for that? 
It would be perfect to have something like to declare only once to be used in multiple file uploaders. For example to use in a form with multiples files uploads with Bootstrap (<img><input text to receive the generated pah image><button to upload)

Demo: https://jsfiddle.net/BUUdesign/be8yLkup/

Thanks a lot :-D

**Comment by focussing** [comment]
I haven't been able to upload anything using uppload.
For all uploaders I have been using I use the following php script.
<?php

header('Access-Control-Allow-Origin: *');

// from http://www.startutorial.com/articles/view/how-to-build-a-file-upload-form-using-dropzonejs-and-php

$ds = DIRECTORY_SEPARATOR;
$storeFolder = 'uploads';

if (!empty($_FILES)) {
	$tempFile = $_FILES['file']['tmp_name'];
	$targetPath = dirname(__FILE__) . $ds . $storeFolder . $ds;
	$targetFile = $targetPath . $_FILES['file']['name'];
	move_uploaded_file($tempFile, $targetFile);
}
?>

**Comment by focussing** [comment]
<?php

header('Access-Control-Allow-Origin: *');

// from http://www.startutorial.com/articles/view/how-to-build-a-file-upload-form-using-dropzonejs-and-php

$ds = DIRECTORY_SEPARATOR;
$storeFolder = 'uploads';

if (!empty($_FILES)) {
	$tempFile = $_FILES['file']['tmp_name'];
	$targetPath = dirname(__FILE__) . $ds . $storeFolder . $ds;
	$targetFile = $targetPath . $_FILES['file']['name'];
	move_uploaded_file($tempFile, $targetFile);
}
?>

**Comment by focussing** [comment]
```
<?php

header('Access-Control-Allow-Origin: *');

// from http://www.startutorial.com/articles/view/how-to-build-a-file-upload-form-using-dropzonejs-and-php

$ds = DIRECTORY_SEPARATOR;
$storeFolder = 'uploads';

if (!empty($_FILES)) {
	$tempFile = $_FILES['file']['tmp_name'];
	$targetPath = dirname(__FILE__) . $ds . $storeFolder . $ds;
	$targetFile = $targetPath . $_FILES['file']['name'];
	move_uploaded_file($tempFile, $targetFile);
}
?>
```

**Comment by IvanMartoyas** [comment]
You needs add header 
fetch(' URL ... ',
            {
                method: "POST",
                **headers: new Headers({
                    Accept: 'application/json',
                    'Content-Type': 'multipart/form-data'
                }),**
                body:  formData
            }
