### ISSUE TITLE
Pulling in the wrapper for React breaks

### ISSUE THREAD

**Issue by scotttball** [elninotech/uppload#32]
**Describe the bug**
When I try to import the wrapper for React in my project, it's not correctly output so it fails to import.

It looks like during this commit when you updated webpack, you inadvertently took out the correct index.js and that is what caused it to break. 

https://github.com/elninotech/uppload/commit/3f69965116a5aea6f4ae043d45fb413dbb7ae6f4#diff-2d30e644caa23a698065055f2b86cb74

**To Reproduce**
1. `import UpploadReact from 'uppload-react'` at the top of the file and try to use the wrapper

**Expected behavior**
I expected to see the wrapper for React

**Comment by thlassche** [comment]
@scotttball PR would be greatly appreciated!

**Comment by AnandChowdhary** [comment]
Hi, @scotttball, this is fixed in v2! We're going to release it very soon, and you can have a look at the Frontend frameworks documentation here: https://uppload.js.org/wrappers/

I'll close this issue as soon as we release v2. You can already try it on the beta channel.
