### ISSUE TITLE
Maximum call stack size exceeded when using uppload on a bootstrap 3.3 modal in vue

### ISSUE THREAD

**Issue by akashrajum** [elninotech/uppload#331]
**Describe the bug**
Hello, 
         I am using the latest version of uppload, which is currently v3.2.1 and when using uppload on top of a bootstrap 3.3 modal in Vue, it throws "Uncaught RangeError: Maximum call stack size exceeded." on opening modal and selecting a method to upload, text fields like search on Unsplash become inactive and error is thrown in console.

**To Reproduce**
1. Go to 'https://7nmz9.csb.app/' (codesandbox: https://codesandbox.io/s/uppload-vue-forked-7nmz9)
2. Click on 'Large modal'
3. Click on 'Select an image'
4. Click on 'Unsplash'
5. See error in console and also unable to search in unsplash

**Expected behavior**
To work without any errors.

**Comment by AnandChowdhary** [comment]
From the first looks, this error looks like it's from `focus-trap`, the dependency that traps focus when the modal is opened. It seems like it's not playing well with jQuery or some jQuery plugin you have installed.

Perhaps you can try removing jQuery or certain plugins until the error is gone; the other option is that we can make focus trapping optional, and you can disable that specifically for your use case.

**Comment by akashrajum** [comment]
Can you please provide instructions on how to disable focus trapping? Thanks.

**Comment by akashrajum** [comment]
Hey, quick update - I tried removing focus trap and now the error is gone but the input is disabled and no errors, any idea why this might be happening? Thanks.

codesandbox - https://8teju.csb.app/ (https://codesandbox.io/s/uppload-vue-forked-8teju)

**Comment by akashrajum** [comment]
Hey, I was able to solve it - https://github.com/sweetalert2/sweetalert2/issues/374#issuecomment-357459577

Basically had to disable bootstrap modal focus function.
