### ISSUE TITLE
Pass a link or base64 image via api

### ISSUE THREAD

**Issue by Leon-Bor** [elninotech/uppload#348]
Hi,

I'm creating an app with Ionic and I would like to use uppload in it.
So im taking a picture with the phones camera and get a base64 image. Then I would like to pass it directly to the uppload modal and edit it (crop, brightness...) and afterwards upload it to my backend.

Is this currently supported?

**Comment by AnandChowdhary** [comment]
Yes, you can use [`URL.createObjectURL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to create a local URL from the data URL. Then, you can use the `value` property, like so:

```ts
import { Uppload } from "uppload";

const uploader = new Uppload({
  value: "blob:http://localhost:3000/example"
});
```

Make sure Uppload only has the plugins for the editing tools you need. Then, you can programmatically call `uploader.open()` and let users upload the image.
