### ISSUE TITLE
Uppload-Vue gives "You may need an appropriate loader to handle this file type." error

### ISSUE THREAD

**Issue by jimmiejackson414** [elninotech/uppload#35]
**Describe the bug**
When attempting to use the Uppload-Vue library, I receive multiple "You may need an appropriate loader to handle this file type" errors. 

**To Reproduce**
1. Run `yarn add uppload-vue`
2. Import `import UpploadVue from 'uppload-vue'` into component and define component. 
3. Open console

**Expected behavior**
N/A

**Screenshots**
<img width="594" alt="Screen Shot 2019-07-02 at 10 22 09 PM" src="https://user-images.githubusercontent.com/10987731/60561085-f31bba00-9d17-11e9-8ad9-5bb79a8d2b91.png">

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 67.0.4

**Additional context**
When I open the `uppload.vue` file in the node module, Vetur gives me errors mentioning that it "cannot find name 'template'. I'm truly not good at understanding the inner workings of a library, however I'm wondering if it's because Vue isn't included in the package.json?

**Comment by AnandChowdhary** [comment]
It seems like you don't have a Vue loader in your webpack configuration?

I just added `uppload-vue` from NPM and it looks it works perfectly: https://codesandbox.io/s/vue-template-mb72e

```vue
<template>
  <div>
    <Uppload :settings="{}" @uploaded="() => {}">
      <button>Upload an image</button>
    </Uppload>
  </div>
</template>

<script>
import Uppload from "uppload-vue";
export default {
  components: {
    Uppload
  }
}
</script>
```

**Comment by jimmiejackson414** [comment]
Hmm I've definitely got vue-loader installed, I'm adding Upploader to a pretty extensive side Vue project. It is using vue-loader v. 14.2.3 and the version being used in your codesandbox example is 15.0.9, however I'm not convinced that would be the reason? Here is my webpack.config.js:
```
module.exports = {
  mode: 'development',
  resolve: {
    extensions: ['.js', '.vue'],
  },
  module: {
    rules: [
      {
        test: /\.vue?$/,
        exclude: /(node_modules)/,
        use: 'vue-loader',
      },
      {
        test: /\.js?$/,
        exclude: /(node_modules)/,
        use: 'babel-loader',
      },
      {
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }],
      },
      {
        test: /\.sass$/,
        use: [
          'vue-style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {
              indentedSyntax: true,
            },
          },
        ],
      },
      {
        test: /\.svg$/,
        loader: 'svg-inline-loader',
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
    }),
    new Dotenv(),
  ],

  devServer: {
    historyApiFallback: true,
  },
  externals: {
    // global app config object
    config: JSON.stringify({
      apiUrl: 'http://localhost:3000',
    }),
  },
}
```

**Comment by jimmiejackson414** [comment]
Just as a followup, here are some of the things that I've tried since posting this report:
- Uninstalling and reinstalling the package.
- Bumping my vue-loader version up to the same version as Uppload.
- Dropping the vue-loader version of Uppload to the same version that I am using. 
- Deleting node_modules and running `yarn` again.
- Copying the example you provided above, which is slightly different from the documentation. In the documentation it imports "UpploadVue" and then has you rename the component to just "uppload" in the components property. I have tried both but am getting the same error.

None of these have worked for me and i'm still getting the errors from the screenshot i posted. Thanks for your help and the wonderful looking library!

**Comment by jimmiejackson414** [comment]
Hopefully I'm not just shouting into the void here, but I think I may have discovered the issue. Uppload is using the following versions of @babel and babel-loader:
```
"@babel/core": "^7.0.0-beta.31",
 "babel-loader": "^8.0.0-beta.0",
```
I am using a slightly older version:
```
"babel-core": "^6.26.0",
"babel-loader": "^7.1.5",
```

I looked at another package that I'm using, vue-progressbar, and they are also using the same major versions of babel that I am. Now I'm not sure whether to modify Uppload or try and upgrade my version of babel which presents its own set of challenges. 

Anyways, hopefully this helps someone else out!
