### ISSUE TITLE
Node sass missing - module too opinionated?

### ISSUE THREAD

**Issue by mxmtsk** [elninotech/uppload#36]
**Describe the bug**
When importing Uppload into my (react) app I get the error:

`
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
`

My project runs PostCSS and is a `create-react-app` project. Is it really necessary to automatically import the CSS/Sass file when importing the module? I love the idea of the package but I think it's a bit too opinionated for widespread use. I really don't like the idea of setting up a another css preprocessor to use this module.

What do you think about adding CSS separately to JS, like other modules are doing it as well (see for example the `slick-carousel`)?  Therefore I could import your CSS to my CSS file like this for example:

```
@import "~uppload/uppload.css";
```

You could still use sass for development and generate a css file when you build the project before you release a new version.

**Comment by AnandChowdhary** [comment]
In Uppload v2, this is now fixed. I'll close this issue as soon as v2 is released. Here is an excerpt from the the theme docs:

If you want to use the built-in themes, you can import the CSS in your JavaScript file using a bundler like Webpack (you'll need an additional loader, like `style-loader`):

```ts
import { Uppload } from "uppload";
import "uppload/dist/uppload.css"; // Basic styles
import "uppload/dist/themes/light.css"; // Light theme

const uppload = new Uppload();
```

You can also use the Sass source code instead:

```css
@import "uppload/src/styles/uppload.scss";
@import "uppload/src/themes/light.scss";
```

Or, use a CDN for styling:

```html
<head>
  <link rel="stylesheet" href="https://unpkg.com/uppload/dist/uppload.css">
  <link rel="stylesheet" href="https://unpkg.com/uppload/dist/themes/light.css">
</head>
```
