### ISSUE TITLE
How is file passed to endpoint?

### ISSUE THREAD

**Issue by jimmiejackson414** [elninotech/uppload#37]
**Describe the bug**
I've spent a few days trying to figure out why the actual file isn't being passed to my endpoint. Using the examples from the docs, I have tried both setting just:
```
endpoint: {
    url: url,
    method: 'put',
}
```

as well as creating my own uploadFunction as such:
```
uploadFunction: (file, metadata) => {
    let url = `${config.apiUrl}/packs/${this.packId}/items/${this.item.id}/upload_image?upload_preset=${this.preset}`; 
    return new Promise((resolve, reject) => {
          fetch(url, {
              method: 'PUT',
              body  : file
          })
              .then(response => {
                response.json()
              })
              .then(json => {
                  let url = json.url;
                  resolve(url);
              })
              .catch(error => reject(error));
      });
 }
```
Neither seem to work, and the only params I'm seeing are ones present in my endpoint url. When I `console.log` file, metadata, response and json in the .then methods:
- file returns a `Blob` 
- metadata returns an Object with the filename, file type and mime type
- response.json() returns a `pending Promise` 
- json returns an error that the `Body has already been consumed.`

**To Reproduce**
1. Import uppload-vue
2. Register component and use in template.
3. Add either endpoint config or uploadFunction method.

**Expected behavior**
N/A

**Screenshots**
<img width="980" alt="Screen Shot 2019-07-06 at 11 53 24 AM" src="https://user-images.githubusercontent.com/10987731/60759083-b33d2700-9fe4-11e9-9ff4-3a6fcfe37ad1.png">

**Desktop (please complete the following information):**
 - OS: OSX Mojave 10.14.5 
 - Browser Firefox Quantum 67.0.4 (64-bit)

**Additional context**
This very well may be lack of knowledge with file uploading in general, however if that's the case, some better documentation (specifically in the Vue wrapper) would be extremely helpful. As it is now, the included example in the Vue wrapper is an .html file rather than the normal .vue SFC

**Comment by AnandChowdhary** [comment]
This is fixed in Uppload v2. I'll close this issue as soon as v2 is released. Here's an excerpt from the docs for uploaders:

Instead of using the XHR Uploader or Fetch Uploader, you can also write your own uploader. The uploader function should return a Promise which resolves to the URL of the uploaded file on the server.

```ts
import { Uppload } from "uppload";

const customUploader = (file: Blob): Promise<string> => {
  // Here, we take the file and send it to the server
  return new Promise((resolve, reject) => {
    // Send the file and get the URL
    resolve("uploaded-file-url");
  });
}
```

As you'll see, the function now takes a simple `Blob` containing the file to upload, and expects a Promise resolving to a String to return.

You can also return progress:

```ts
const customUploader = (
  file: Blob,
  updateProgress: (progress: number) => void
): Promise<string> => {
  // Here, we take the file and send it to the server
  return new Promise((resolve, reject) => {
    // Keep updating the progress
    updateProgress(10); // Progress is now at 10%
    // Send the file as soon as it is uploaded
    resolve("uploaded-file-url");
  });
}
```
