### ISSUE TITLE
Font awesome conflicting with existing libs

### ISSUE THREAD

**Issue by gorkamolero** [elninotech/uppload#38]
Hello!

I managed to trace down a bug in my app to Uppload loading font awesome by itself.

Do you think it is possible to load conditionally?

Thank you

**Comment by AnandChowdhary** [comment]
You can now use `ignoreFontAwesome` in the constructor object to prevent loading Font Awesome from the CDN:

```js
new Uppload({
  ignoreFontAwesome: true
})
```

Make sure you provide your own Font Awesome, because otherwise no icons would be visible.

**Comment by gorkamolero** [comment]
Hello,

Using the Vue wrapper, and passing this into settings, doesn't work. Any ideas?

`data: () => ({
    uppload: {
      settings: {
        ignoreFontAwesome: true,
        minimumDelay: 2000,
        uploadFunction: file => (
          new Promise((resolve, reject) => {
            let url = URL.createObjectURL(file)
            resolve(url)
          })
        )
      }
    }
  }),`
