### ISSUE TITLE
Can't create two new Uppload without one being overwritten by the other one

### ISSUE THREAD

**Issue by eltoredo** [elninotech/uppload#40]
**Describe the bug**
I created two Uppload initializer, one to upload image in a specific part of the website, another one to change the background image.
Then, whenever I click on the button to call the first Uppload or the button to call the second Uppload, it only calls the second one.

**To Reproduce**
Create 2 const X = new Uppload with the same endpoint
Create 2 X.on fileuploaded to get the fileURL and do something with it
Only the second fileuploaded will execute its code (there are two listeners on it)

**Expected behavior**
I expeceted one of them to change my background image and the other one to put an image in a specific part of the website.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 69.0.1 64 bits

**Additional context**
Here is a hastebin of the code (without the 'on error' parts) : https://hastebin.com/umafefanow.js
If I delete one of the new Uppload, only the other one will be called. The Uppload name doesn't change anything, in fact.

Thanks for reading!

**Comment by eltoredo** [comment]
Is there a way to specify data in the 'endpoint' configuration to POST normal img or background img in my php script?

`endpoint: {
            method: "POST",
            url: './uploadv2.php',
            data: 'bgimage',
        },`

Something like that, and in my PHP script, I would get it like:

`if(isset($_POST['bgimage'])) do something
else if(isset($_POST['normalimage'])) do something`

**Comment by AnandChowdhary** [comment]
This is fixed in Uppload v2. I'll close this issue as soon as v2 is released. Here's an excerpt from the docs:

You can have multiple instances of Uppload on a webpage.

```ts
import { Uppload, Local, Fetch, en } from "uppload";

const profilePicture = new Uppload({ lang: en });
profilePicture.use([new Local(), new Fetch("http://localhost:3000/upload")]);

const coverImage = new Uppload({ lang: en });
coverImage.use([new Local(), new Fetch("http://localhost:3000/upload")]);
```

They no longer rely upon any global objects or classes and all event listeners are scoped to their own instances.

**Comment by eltoredo** [comment]
Thanks for the news and the hard work, I've seen the new Github page about Uppload v2 and I'm hyped!
I've managed this case by doing a switch in the on("fileUploaded") listener, it's not that dirty and it's working so it's fine :)

**Comment by jeffbabuyo** [comment]
When will be the V2 release?

**Comment by AnandChowdhary** [comment]
v2 is ready! You can already `npm install uppload@latest` and try the beta, and we're going to launch it as soon as I've added some more documentation and i18n languages, which should be days. My plan is by next weekend (Dec 14–15) for the official launch. 😄

**Comment by eltoredo** [comment]
I just saw that we could download it but I couldn't get it to work on my project so I stayed with the first version for the moment haha

**Comment by AnandChowdhary** [comment]
> I just saw that we could download it but I couldn't get it to work on my project so I stayed with the first version for the moment haha

@eltoredo, can you share what went wrong? I'd love to help you and make sure you're able to use v2. Here are some code examples to get you started: https://uppload.js.org/examples

**Comment by eltoredo** [comment]
In short, I installed the new version without changing my code. I use the `<script src="./node_modules/...">` way to use the file that I need, so I took the `index.js` one because there wasn't the `uppload.min.js` one anymore.
Then, I got an error at the first line of the js file saying that `import`s must be declared at the top level of the document (which is the case). So I tried to use the import way, as in all of your new examples but I get the same error in my own files. I don't use any import in my tool.

Then, Uppload is not defined but I guess that it's because the basic implementation didn't work.

What do you think?

**Comment by AnandChowdhary** [comment]
With Uppload v1, you could just CDN-load and get started, because we set a `window.Uppload` object. However, we don't do this in v2 because you get to build your own bundle based on the features you want to keep. This is why you cannot just use `<script src=` to load Uppload v2.

Here are your options:

1. You can use an asset bundler like Parcel, Webpack, or Rollup which can help you import Uppload, set up your custom build, and transpile to browser-loadable ES5. Here's a demo: https://codesandbox.io/s/clever-agnesi-ijdp2

2. If you want to use `<script>` directly, you can also do that using `<script type="module">`. I've made a JSFiddle demo for you here: https://jsfiddle.net/4yqc1dvm/3/. This uses [jspm.io](https://jspm.io/) and requires no bundler. Note the [browser support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#bcd:html.elements.script) for script type.modules.

**Comment by eltoredo** [comment]
Thanks for the awesome examples, I'll try the second option first!
Do you know what prevents my tool to use the `import` way of loading scripts?
