### ISSUE TITLE
Help link on Camera error page is broken

### ISSUE THREAD

**Issue by wireland1992** [elninotech/uppload#403]
**Describe the bug**
In Uppload 3.2.1, the error message on the camera service contains a broken link ("Need Help?" goes to https://uppload.js.org/help/camera which doesn't exist anymore).

**To Reproduce**
1. Deny camera access
2. Go to Camera service

**Expected behavior**
The "Need Help?" link should go to the proper help page.

**Additional context**
I think it may be a good idea to rewrite the error message as well, currently it says:
"We're not able to read your camera's video. This may be because you didn't grant the required permission, or because your device doesn't support camera access."

I recommend "We're not able to read your camera's video. This may be because you didn't grant the required permission, or because your camera is in use by another application."

**Comment by AnandChowdhary** [comment]
Thanks for the report! The link should go to https://uppload.js.org/help/services/camera and not https://uppload.js.org/help/camera. Can you make a PR to fix this, and the error message? 😄
