### ISSUE TITLE
Does Uppload support upload to Google Drive?

### ISSUE THREAD

**Issue by erikswed** [elninotech/uppload#503]
hi
I read the docs but can't make out if Uppload also can send files to Google Drive I saw there was plugin for uploading to Firebase so. I wanted to ask if someone did it for Google Drive to.

**Comment by AnandChowdhary** [comment]
No, with Uppload, you have to set up your own file uploading backend (we don't manage that). We do, however, have plugins for directly uploading to Firebase. For your use case, you'll have to build a backend API to take the uploaded file and store it in Google Drive.

**Comment by erikswed** [comment]
Is there some guide on how to create this kind of Uppload plugins, I mean
create same as the Firebase upload plugin but for Google Drive
