### ISSUE TITLE
Uppload hangs while uploading PDFs

### ISSUE THREAD

**Issue by zekenie** [elninotech/uppload#75]
When I upload images, everything works. But, when I upload pdfs of any size, it hangs on the "uploading" screen.

![image](https://user-images.githubusercontent.com/962281/73140745-f2df6500-4041-11ea-8610-d3d902b8ea15.png)

The `before-upload` event does fire. No error event fires. No error message is ever displayed. No XHR request is ever made to the backend. The `settingsFunction` never fires.

I have the following configuration

```ts
const uppload = new Uppload({
  lang: en,
  defaultService: "local",
  
  uploader: xhrUploader({
    responseKey: "file",

    endpoint: `${process.env.API_URL}/attachments`,
    settingsFunction(xmlHttp) {
      console.log("do i get to settingsFunc");
      xmlHttp.setRequestHeader("authorization", Auth.getToken());
    },

  })
});

uppload.use([
  new Local({
    mimeTypes: ["image/png", "image/jpeg", "image/gif", "application/pdf"]
  })
]);

uppload.on("*", console.log);
```

I attached an event emitter to all events and got the following console output
![image](https://user-images.githubusercontent.com/962281/73140874-4900d800-4043-11ea-86ec-652a9d7a00cb.png)

**Comment by zekenie** [comment]
Update! I thin the error has to do with image compression. I modified my configuration to add the `compressor` property. I made it resolve a promise with the original file, and the upload worked. I think there should be a way to have image compression for certain mime types

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue too, @zekenie! It makes a lot of sense to handle this for non-images. This is deployed in `v2.2.0`.

**Comment by zekenie** [comment]
@AnandChowdhary Hey! sorry to reopen this, but I have a new related issue. With `v.2.2.0`, when I enable compression again, the original filename is recorded as `Blob` and not the original file's name from disk

**Comment by AnandChowdhary** [comment]
I've opened this as a separate issue as #77.
