### ISSUE TITLE
Preserve file name when converting to Blob

### ISSUE THREAD

**Issue by AnandChowdhary** [elninotech/uppload#77]
**Describe the bug**
In Uppload v2, an uploaded file is converted to a native `Blob`, which means metadata such as file name are wiped. If this were preserved, there could be a better name for uploaded files.

**To Reproduce**
1. Go to 'Upload a file

**Proposed solutions**
1. Use `File` API instead of `Blob` (browser support?)
2. Add helper functions for autogenerating file names

**Comment by AnandChowdhary** [comment]
Another interesting thing to note is that only the Local service (https://uppload.js.org/services/local) tells us the file name because the user selects a file from their computer. All other services, like Instagram and URLs, will probably need generated file names, and search services (like Unsplash and Pexels) can use their image titles as names.

**Comment by AnandChowdhary** [comment]
@zekenie, the file name is now preserved when using the Local service, and we're also generating a file name for imported photos from their descriptions, photographers, or tags/labels.

**Comment by sigma-technology** [comment]
@AnandChowdhary Is it a known issue that the file name is lost when using the Crop etc. plugins? I just get a raw blob file without any file name. If you have any ideas of a way around this I would be interested to learn of it.

**Comment by sigma-technology** [comment]
I meant to mention that I'm using the XHR uploader as well.

**Comment by AnandChowdhary** [comment]
Cases I've tested:

1. Uploading a PDF (which means no image effects) retains file attributes like name, last modified, size, and type
2. Uploading a JPEG and cropping it retains the file attributes while cropping (success!) like in cb7c108, but when uploading the file, the attributes are gone

This definitely needs fixing.

**Comment by AnandChowdhary** [comment]
This is deployed in `v2.7.2`.

**Comment by sigma-technology** [comment]
All looks to be working from my testing. Thank you!
