### ISSUE TITLE
Support for JS library

### ISSUE THREAD

**Issue by JerryGoyal** [elninotech/uppload#78]
Could there be a js library over CDN which can be used for static sites not built using react/vue/angular.
I noticed from the docs that you've support for firebase storage for uploading, no other library has this integration.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @JerryGoyal. I'm not sure I understand exactly what you're looking for here — currently, you need a bundler like Webpack or Parcel to create a bundle with your site, including Uppload and its ES6 (Node-style) imports. Furthermore, you need to import specific packages from Uppload based on what features you want in your build (see https://uppload.js.org/getting-started). This is why it's not possible to directly use Uppload from a CDN.

However, using a bundler has nothing to do with using frameworks like React. You can use Uppload in a static site after bundling your JavaScript. For example, our own site (https://uppload.js.org) has a demo on the top and doesn't use a framework, just a static site generator ([@staart/site](https://github.com/staart/site)) with custom JS (https://github.com/elninotech/uppload/tree/master/demo).

**Comment by JerryGoyal** [comment]
thanks Anand for good explanation about the bundlers. I used to import js libraries via CDN and use them plain and simple. This bundle thing is quite new to me but I'll try to implement webpack and use uppload via that.

**Comment by AnandChowdhary** [comment]
@JerryGoyal, I've made a new release [v2.3.0](https://www.npmjs.com/package/uppload/v/2.3.0) where we fully-support using Uppload in the browser with nothing but CDNs — no compiling required.

This is how you'd go about it:
- Add the JavaScript browser package (https://unpkg.com/uppload@2.3.0/dist/browser.js)
- Add the basic CSS (https://unpkg.com/uppload@2.3.0/dist/uppload.css)
- Add the theme you like (https://unpkg.com/uppload@2.3.0/dist/themes/light.css)

And then initialize the plugin (all window properties are `uppload_` scoped):

```js
var picture = new window.uppload_Uppload({
  lang: window.uppload_en
});

picture.use(new window.uppload_Instagram());
```

Here's the demo: https://jsfiddle.net/anandchowdhary/y3c4wmtg/2/ (see "Resources" in sidebar)

**Comment by AnandChowdhary** [comment]
We also have docs for the same now: https://uppload.js.org/browser-usage

**Comment by JerryGoyal** [comment]
thanks Anand for the extended support 👍
