### ISSUE TITLE
Transparent pngs upload with black background

### ISSUE THREAD

**Issue by nicholasgriffinVF** [elninotech/uppload#81]
I noticed that in uppload V2, a transparent PNG will upload with a black background, not a transparent one.

To reproduce:

- open uppload
- select a local file upload
- choose a transparent PNG
- upload the image
- the PNG will output with a black background

Expected behaviour:

- transparent pngs retain their transparency or when used with something that doesn't allow for it, the background is white not black

**Comment by AnandChowdhary** [comment]
Quick update: This seems to be related to compression or plugins, which use the HTML5 Canvas API's export function, which adds a background color with "image/jpeg". I'm confident PNGs should be transparent with compression disabled, or with WebP compression, but I'll debug this soon:

> This blackening occurs because the 'image/jpeg' conversion involves setting the alpha of all canvas pixels to fully opaque (alpha=255). The problem is that transparent canvas pixels are colored fully-black-but-transparent. So when you turn these black pixels opaque, the result is a blackened jpeg.

– @markE on https://stackoverflow.com/a/32160200/1656944

**Comment by AnandChowdhary** [comment]
I can confirm the above is true. Changing the `compressionMime` to use WebP instead of JPEG fixes this issue, which you do like this:

```ts
const image = new Uppload({
  compressionMime: "image/webp"
});
```

More about compression: https://uppload.js.org/compression

**Comment by AnandChowdhary** [comment]
This is deployed in `v2.3.2`. PNGs, GIFs, or other non-WebP transparent images are now passed through uncompressed. You can even use effects like cropping with transparent images. :)
