### ISSUE TITLE
Node.js support for back-end applications

### ISSUE THREAD

**Issue by sourabhbagrecha** [elninotech/uppload#87]
Please add support for node.js backend as well, because even after using AWS and GCP SDKs, it is not straight forward and easy to upload files on the go. It would be great if the community can contribute to this issue and make **uppload** the first choice for uploading files.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @sourabhbagrecha. Uppload in itself doesn't manage your backend and therefore works with Node.js backends already. Once you've set up your file uploading API, use that endpoint with the XHR Uploader: https://uppload.js.org/uploaders/xhr
