### ISSUE TITLE
which version node & npm used in project ?

### ISSUE THREAD

**Issue by todokku** [elninotech/uppload#88]
Hi El Niño,
which version node & npm used in project ?
waiting for your response
finest regards
goodbye

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @todokku!

In development, we're using the LTS version `12.16.0`. However, as you'll see from our tests in [`.github/workflows/nodejs.yml`](https://github.com/elninotech/uppload/blob/master/.github/workflows/nodejs.yml), we're testing Node.js version 10.x as well.

Node.js 8.x is deprecated and therefore not supported.
