### ISSUE TITLE
images.weserv.nl is being throttled by cloudflare, please change URL to wsrv.nl

### ISSUE THREAD

**Issue by RichardJohnn** [elninotech/uppload#880]
per https://github.com/weserv/images/issues/360

you are gonna want to change https://github.com/elninotech/uppload/blob/master/src/helpers/http.ts#L52
from
`.fetch(`https://images.weserv.nl/?url=${encodeURIComponent(url)}`)`
to 
`.fetch(`https://wsrv.nl/?url=${encodeURIComponent(url)}`)`

**Comment by victorlap** [comment]
Hi @RichardJohnn If you can submit a PR that would be great.

**Comment by RichardJohnn** [comment]
https://github.com/elninotech/uppload/pull/882 🙌

**Comment by victorlap** [comment]
Closed in #882
