### ISSUE TITLE
Ability to remove services programatically

### ISSUE THREAD

**Issue by sigma-technology** [elninotech/uppload#89]
**Is your feature request related to a problem? Please describe.**
I would like to open Uppload multiple times on the same page using different triggers, and each trigger will have different settings as to which services are available.  When I call `.use()` and pass it an array of services, this often doubles-up the services so they appear multiple times.

**Describe the solution you'd like**
A way to remove one or more services, or better yet, reset the services so that you can start again. I am able to add new services any time, but it's not possible to remove them. So either `Uppload.reset()` or `Uppload.remove()`.

**Describe alternatives you've considered**
There don't appear to be any, other than destroying the object and recreating it from scratch, which seems like a waste considering there's already a `.updateSettings()` method.

**Additional context**
![image](https://user-images.githubusercontent.com/17182577/75170657-57b1dc00-5722-11ea-9ff5-ba214b07331e.png)

Thank you for creating this awesome repository.

**Comment by AnandChowdhary** [comment]
Great idea! I'll implement and release this within a couple of hours.

**Comment by AnandChowdhary** [comment]
@sigma-technology, this is deployed in `v2.6.0`:

There are two new functions:

1. remove(slug: string): void
2. updatePlugins(pluginUpdateFunction: IPluginUpdateFunction): void

To remove a specific plugin (both services and effects are plugins), you can use `remove`:

```ts
const uppload = new Uppload();
uppload.use([new Instagram(), new Crop()]);
// Later
uppload.remove("instagram");
```

To update all plugins programmatically, use `updatePlugins`:

```ts
uppload.updatePlugins(plugins => plugins.filter(plugin => {
  plugin.name === "instagram"
}));
```

or like this:

```ts
uppload.updatePlugins(plugins => {
  const result = plugins.length > 4 ? [] : plugins;
  result.push(new Crop(), new Unsplash());
  return result;
});
```

So, if you want to remove all plugins (i.e., reset), you can do this:

```ts
uppload.updatePlugins(plugins => []);
```

We also make sure there are no duplicates now, so even if you add a plugin twice, it'll only be registered once. Let me know if you need anything else! :)

**Comment by AnandChowdhary** [comment]
I've also updated the API docs: https://uppload.js.org/api

**Comment by sigma-technology** [comment]
@AnandChowdhary I was just trying to find this issue because I was going to come and apologise because I just found that part in the API docs and thought I had missed it previously!

Thank you so much for the extremely fast response, this is a huge improvement.  I will get on to testing it now and let you know if I find any issues.
