### ISSUE TITLE
New release planned? Latest release on npmjs.com is three years old

### ISSUE THREAD

**Issue by Kephson** [elninotech/uppload#890]
Is it planned to release a new official version of uppload to https://www.npmjs.com/package/uppload in the next weeks?
Latest released version is three years old and there are a lot of changes in the master branch on Github.

**Comment by cmarouan** [comment]
+1

**Comment by victorlap** [comment]
Hi @Kephson, @cmarouan We're currently revamping the docs and build steps. After that is done we're going to do a new release
