### ISSUE TITLE
Crop, Brightness etc. still visible/clickable when adding non-image

### ISSUE THREAD

**Issue by sigma-technology** [elninotech/uppload#90]
**Describe the bug**
Version 2.6.0
I have allowed PDF files to be uploaded as well as images.  If you add a PDF file, the image editing tools are still shown and are clickable, which will probably be confusing for users.

**To Reproduce**
1. Ensure e.g. `Crop`, `Brightness` are enabled
2. Allow `application/pdf` in mime types for Local service
3. Drag PDF file in or select one
4. Image `Crop`, `Brightness` etc. tools are still displayed, clickable and usable

**Expected behavior**
For any non-image to be uploaded instantly, bypassing the image editing tools.
So, for the image editing tools to be displayed **only** if the upload is of type `image/*` OR when `multiple` is enabled, for them to only be displayed if there is a `image/*` in the array of files to be uploaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/17182577/75205814-a8e6bd80-576c-11ea-8887-eec687a951fe.png)

**Desktop (please complete the following information):**
 - OS: \[Windows 10 x64]
 - Browser \[Chrome]
 - Version \[80]

**Additional context**
N/A

**Comment by AnandChowdhary** [comment]
This is deployed in [`v2.6.1`](https://www.npmjs.com/package/uppload/v/2.6.1) 😄

**Comment by sigma-technology** [comment]
Tested - looks to be working perfectly, thank you!
