### ISSUE TITLE
Gitpod setup is broken

### ISSUE THREAD

**Issue by nisarhassan12** [elninotech/uppload#93]
It got broke in this commit in this commit https://github.com/elninotech/uppload/pull/92/commits/a7893d855b947fc0cca0fe5a87c80e1e02040cf8

![image](https://user-images.githubusercontent.com/46004116/75248448-01ae6880-57f6-11ea-8363-ae04e7c15fae.png)

I will soon make a PR with the Fix.

**Comment by AnandChowdhary** [comment]
Ok, thanks for your help! Basically, the build site steps aren’t required because they’re only for the documentation website. Only the “demo” script needs to run, which starts a local server with HMR etc.

**Comment by nisarhassan12** [comment]
Thanks! yes! you're right! the build is failing due to a hyphen in front of the `- command` it's not needed with the updates that you made. I have made this PR with the Fix https://github.com/elninotech/uppload/pull/94
